version: '3'

services: 

  postgres:
    container_name: postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: likeapp
    image: postgres:latest
    networks: 
      - production-network
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  likeapp:
    build:
      dockerfile: ./Dockerfile
      context: .
    command: ["npm", "run", "dev"]
    container_name: likeapp
    depends_on:
      - "postgres"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: likeapp
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
    image: rodrigocipriani/likeapp
    networks: 
      - production-network
    ports: 
      -  "8080:8080"
      -  "3010:3010"
    volumes:
     - .:/home/app

networks: 
  production-network:
    driver: bridge